name: test

on:
  pull_request:
  push:
    branches:
      - "main"
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4

      - name: Go version
        run: go version

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: go test -shuffle on ./...
